name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build Mod
      run: ./Publish.ps1
      shell: powershell
      working-directory: p4gpc.custompartypanel
    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
       name: custom-party-panel-build
       path: "./p4gpc.custompartypanel/Publish/ToUpload"   